version: "2"
linters:
  enable:
    - errcheck
    - staticcheck
    - ineffassign
    - govet
    - unused
    - prealloc
    - unconvert
    - misspell
    - whitespace
    - nakedret
    - dogsled
    - copyloopvar
    - dupl
    - errchkjson
    - errorlint
    - goconst
    - iface
    - testifylint
    - sqlclosecheck
formatters:
  enable:
    - goimports